language: node_js
node_js:
  - 12.3.1
cache:
  - npm
  - yarn
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of the repository, as a secure variable
  local_dir: public
  on:
    branch: master